/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing BearerResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BearerResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BearerResponse
        //private BearerResponse instance;

        public BearerResponseTests()
        {
            // TODO uncomment below to create an instance of BearerResponse
            //instance = new BearerResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BearerResponse
        /// </summary>
        [Fact]
        public void BearerResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BearerResponse
            //Assert.IsType<BearerResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
    }
}
