/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing BodyVerifyVerifyAuthVerifyPost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BodyVerifyVerifyAuthVerifyPostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BodyVerifyVerifyAuthVerifyPost
        //private BodyVerifyVerifyAuthVerifyPost instance;

        public BodyVerifyVerifyAuthVerifyPostTests()
        {
            // TODO uncomment below to create an instance of BodyVerifyVerifyAuthVerifyPost
            //instance = new BodyVerifyVerifyAuthVerifyPost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BodyVerifyVerifyAuthVerifyPost
        /// </summary>
        [Fact]
        public void BodyVerifyVerifyAuthVerifyPostInstanceTest()
        {
            // TODO uncomment below to test "IsType" BodyVerifyVerifyAuthVerifyPost
            //Assert.IsType<BodyVerifyVerifyAuthVerifyPost>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
    }
}
