/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing BodyVerifyRequestTokenAuthRequestVerifyTokenPost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BodyVerifyRequestTokenAuthRequestVerifyTokenPostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BodyVerifyRequestTokenAuthRequestVerifyTokenPost
        //private BodyVerifyRequestTokenAuthRequestVerifyTokenPost instance;

        public BodyVerifyRequestTokenAuthRequestVerifyTokenPostTests()
        {
            // TODO uncomment below to create an instance of BodyVerifyRequestTokenAuthRequestVerifyTokenPost
            //instance = new BodyVerifyRequestTokenAuthRequestVerifyTokenPost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BodyVerifyRequestTokenAuthRequestVerifyTokenPost
        /// </summary>
        [Fact]
        public void BodyVerifyRequestTokenAuthRequestVerifyTokenPostInstanceTest()
        {
            // TODO uncomment below to test "IsType" BodyVerifyRequestTokenAuthRequestVerifyTokenPost
            //Assert.IsType<BodyVerifyRequestTokenAuthRequestVerifyTokenPost>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
