/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing Detail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Detail
        //private Detail instance;

        public DetailTests()
        {
            // TODO uncomment below to create an instance of Detail
            //instance = new Detail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Detail
        /// </summary>
        [Fact]
        public void DetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" Detail
            //Assert.IsType<Detail>(instance);
        }
    }
}
