/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorModel
        //private ErrorModel instance;

        public ErrorModelTests()
        {
            // TODO uncomment below to create an instance of ErrorModel
            //instance = new ErrorModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorModel
        /// </summary>
        [Fact]
        public void ErrorModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorModel
            //Assert.IsType<ErrorModel>(instance);
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
    }
}
