/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.arpg.api.Model;
using com.arpg.api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.arpg.api.Test.Model
{
    /// <summary>
    ///  Class for testing UserRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserRead
        //private UserRead instance;

        public UserReadTests()
        {
            // TODO uncomment below to create an instance of UserRead
            //instance = new UserRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserRead
        /// </summary>
        [Fact]
        public void UserReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserRead
            //Assert.IsType<UserRead>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsSuperuser'
        /// </summary>
        [Fact]
        public void IsSuperuserTest()
        {
            // TODO unit test for the property 'IsSuperuser'
        }

        /// <summary>
        /// Test the property 'IsVerified'
        /// </summary>
        [Fact]
        public void IsVerifiedTest()
        {
            // TODO unit test for the property 'IsVerified'
        }
    }
}
