/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using com.arpg.api.Client;
using com.arpg.api.Client.Auth;
using com.arpg.api.Model;

namespace com.arpg.api.arpg
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Auth:Unity.Login
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BearerResponse</returns>
        BearerResponse AuthUnityLoginAuthJwtLoginPost(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0);

        /// <summary>
        /// Auth:Unity.Login
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BearerResponse</returns>
        ApiResponse<BearerResponse> AuthUnityLoginAuthJwtLoginPostWithHttpInfo(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0);
        /// <summary>
        /// Auth:Unity.Logout
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object AuthUnityLogoutAuthJwtLogoutPost(int operationIndex = 0);

        /// <summary>
        /// Auth:Unity.Logout
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> AuthUnityLogoutAuthJwtLogoutPostWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Secure Endpoint
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object SecureEndpointAuthSecureEndpointGet(int operationIndex = 0);

        /// <summary>
        /// Secure Endpoint
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> SecureEndpointAuthSecureEndpointGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Verify:Request-Token
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object VerifyRequestTokenAuthRequestVerifyTokenPost(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0);

        /// <summary>
        /// Verify:Request-Token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfo(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0);
        /// <summary>
        /// Verify:Verify
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserRead</returns>
        UserRead VerifyVerifyAuthVerifyPost(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0);

        /// <summary>
        /// Verify:Verify
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserRead</returns>
        ApiResponse<UserRead> VerifyVerifyAuthVerifyPostWithHttpInfo(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Auth:Unity.Login
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BearerResponse</returns>
        System.Threading.Tasks.Task<BearerResponse> AuthUnityLoginAuthJwtLoginPostAsync(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Auth:Unity.Login
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BearerResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BearerResponse>> AuthUnityLoginAuthJwtLoginPostWithHttpInfoAsync(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Auth:Unity.Logout
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> AuthUnityLogoutAuthJwtLogoutPostAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Auth:Unity.Logout
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AuthUnityLogoutAuthJwtLogoutPostWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Secure Endpoint
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> SecureEndpointAuthSecureEndpointGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Secure Endpoint
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SecureEndpointAuthSecureEndpointGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Verify:Request-Token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> VerifyRequestTokenAuthRequestVerifyTokenPostAsync(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Verify:Request-Token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfoAsync(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Verify:Verify
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserRead</returns>
        System.Threading.Tasks.Task<UserRead> VerifyVerifyAuthVerifyPostAsync(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Verify:Verify
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserRead)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserRead>> VerifyVerifyAuthVerifyPostWithHttpInfoAsync(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthApi : IAuthApiSync, IAuthApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthApi : IAuthApi
    {
        private com.arpg.api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthApi(string basePath)
        {
            this.Configuration = com.arpg.api.Client.Configuration.MergeConfigurations(
                com.arpg.api.Client.GlobalConfiguration.Instance,
                new com.arpg.api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new com.arpg.api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new com.arpg.api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = com.arpg.api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthApi(com.arpg.api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = com.arpg.api.Client.Configuration.MergeConfigurations(
                com.arpg.api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new com.arpg.api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new com.arpg.api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = com.arpg.api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AuthApi(com.arpg.api.Client.ISynchronousClient client, com.arpg.api.Client.IAsynchronousClient asyncClient, com.arpg.api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = com.arpg.api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public com.arpg.api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public com.arpg.api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public com.arpg.api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public com.arpg.api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Auth:Unity.Login 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BearerResponse</returns>
        public BearerResponse AuthUnityLoginAuthJwtLoginPost(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0)
        {
            com.arpg.api.Client.ApiResponse<BearerResponse> localVarResponse = AuthUnityLoginAuthJwtLoginPostWithHttpInfo(username, password, grantType, scope, clientId, clientSecret);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Auth:Unity.Login 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BearerResponse</returns>
        public com.arpg.api.Client.ApiResponse<BearerResponse> AuthUnityLoginAuthJwtLoginPostWithHttpInfo(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'username' is set
            if (username == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'username' when calling AuthApi->AuthUnityLoginAuthJwtLoginPost");
            }

            // verify the required parameter 'password' is set
            if (password == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'password' when calling AuthApi->AuthUnityLoginAuthJwtLoginPost");
            }

            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (grantType != null)
            {
                localVarRequestOptions.FormParameters.Add("grant_type", com.arpg.api.Client.ClientUtils.ParameterToString(grantType)); // form parameter
            }
            localVarRequestOptions.FormParameters.Add("username", com.arpg.api.Client.ClientUtils.ParameterToString(username)); // form parameter
            localVarRequestOptions.FormParameters.Add("password", com.arpg.api.Client.ClientUtils.ParameterToString(password)); // form parameter
            if (scope != null)
            {
                localVarRequestOptions.FormParameters.Add("scope", com.arpg.api.Client.ClientUtils.ParameterToString(scope)); // form parameter
            }
            if (clientId != null)
            {
                localVarRequestOptions.FormParameters.Add("client_id", com.arpg.api.Client.ClientUtils.ParameterToString(clientId)); // form parameter
            }
            if (clientSecret != null)
            {
                localVarRequestOptions.FormParameters.Add("client_secret", com.arpg.api.Client.ClientUtils.ParameterToString(clientSecret)); // form parameter
            }

            localVarRequestOptions.Operation = "AuthApi.AuthUnityLoginAuthJwtLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<BearerResponse>("/auth/jwt/login", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthUnityLoginAuthJwtLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Auth:Unity.Login 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BearerResponse</returns>
        public async System.Threading.Tasks.Task<BearerResponse> AuthUnityLoginAuthJwtLoginPostAsync(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            com.arpg.api.Client.ApiResponse<BearerResponse> localVarResponse = await AuthUnityLoginAuthJwtLoginPostWithHttpInfoAsync(username, password, grantType, scope, clientId, clientSecret, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Auth:Unity.Login 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username"></param>
        /// <param name="password"></param>
        /// <param name="grantType"> (optional)</param>
        /// <param name="scope"> (optional, default to &quot;&quot;)</param>
        /// <param name="clientId"> (optional)</param>
        /// <param name="clientSecret"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BearerResponse)</returns>
        public async System.Threading.Tasks.Task<com.arpg.api.Client.ApiResponse<BearerResponse>> AuthUnityLoginAuthJwtLoginPostWithHttpInfoAsync(string username, string password, string? grantType = default(string?), string? scope = default(string?), string? clientId = default(string?), string? clientSecret = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'username' is set
            if (username == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'username' when calling AuthApi->AuthUnityLoginAuthJwtLoginPost");
            }

            // verify the required parameter 'password' is set
            if (password == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'password' when calling AuthApi->AuthUnityLoginAuthJwtLoginPost");
            }


            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (grantType != null)
            {
                localVarRequestOptions.FormParameters.Add("grant_type", com.arpg.api.Client.ClientUtils.ParameterToString(grantType)); // form parameter
            }
            localVarRequestOptions.FormParameters.Add("username", com.arpg.api.Client.ClientUtils.ParameterToString(username)); // form parameter
            localVarRequestOptions.FormParameters.Add("password", com.arpg.api.Client.ClientUtils.ParameterToString(password)); // form parameter
            if (scope != null)
            {
                localVarRequestOptions.FormParameters.Add("scope", com.arpg.api.Client.ClientUtils.ParameterToString(scope)); // form parameter
            }
            if (clientId != null)
            {
                localVarRequestOptions.FormParameters.Add("client_id", com.arpg.api.Client.ClientUtils.ParameterToString(clientId)); // form parameter
            }
            if (clientSecret != null)
            {
                localVarRequestOptions.FormParameters.Add("client_secret", com.arpg.api.Client.ClientUtils.ParameterToString(clientSecret)); // form parameter
            }

            localVarRequestOptions.Operation = "AuthApi.AuthUnityLoginAuthJwtLoginPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BearerResponse>("/auth/jwt/login", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthUnityLoginAuthJwtLoginPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Auth:Unity.Logout 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object AuthUnityLogoutAuthJwtLogoutPost(int operationIndex = 0)
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = AuthUnityLogoutAuthJwtLogoutPostWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Auth:Unity.Logout 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public com.arpg.api.Client.ApiResponse<Object> AuthUnityLogoutAuthJwtLogoutPostWithHttpInfo(int operationIndex = 0)
        {
            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthApi.AuthUnityLogoutAuthJwtLogoutPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/auth/jwt/logout", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthUnityLogoutAuthJwtLogoutPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Auth:Unity.Logout 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> AuthUnityLogoutAuthJwtLogoutPostAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = await AuthUnityLogoutAuthJwtLogoutPostWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Auth:Unity.Logout 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<com.arpg.api.Client.ApiResponse<Object>> AuthUnityLogoutAuthJwtLogoutPostWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthApi.AuthUnityLogoutAuthJwtLogoutPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/auth/jwt/logout", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthUnityLogoutAuthJwtLogoutPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Secure Endpoint 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object SecureEndpointAuthSecureEndpointGet(int operationIndex = 0)
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = SecureEndpointAuthSecureEndpointGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Secure Endpoint 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public com.arpg.api.Client.ApiResponse<Object> SecureEndpointAuthSecureEndpointGetWithHttpInfo(int operationIndex = 0)
        {
            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthApi.SecureEndpointAuthSecureEndpointGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/auth/secure-endpoint", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureEndpointAuthSecureEndpointGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Secure Endpoint 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> SecureEndpointAuthSecureEndpointGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = await SecureEndpointAuthSecureEndpointGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Secure Endpoint 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<com.arpg.api.Client.ApiResponse<Object>> SecureEndpointAuthSecureEndpointGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "AuthApi.SecureEndpointAuthSecureEndpointGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/auth/secure-endpoint", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SecureEndpointAuthSecureEndpointGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify:Request-Token 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object VerifyRequestTokenAuthRequestVerifyTokenPost(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0)
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfo(bodyVerifyRequestTokenAuthRequestVerifyTokenPost);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify:Request-Token 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public com.arpg.api.Client.ApiResponse<Object> VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfo(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0)
        {
            // verify the required parameter 'bodyVerifyRequestTokenAuthRequestVerifyTokenPost' is set
            if (bodyVerifyRequestTokenAuthRequestVerifyTokenPost == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'bodyVerifyRequestTokenAuthRequestVerifyTokenPost' when calling AuthApi->VerifyRequestTokenAuthRequestVerifyTokenPost");
            }

            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bodyVerifyRequestTokenAuthRequestVerifyTokenPost;

            localVarRequestOptions.Operation = "AuthApi.VerifyRequestTokenAuthRequestVerifyTokenPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/auth/request-verify-token", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyRequestTokenAuthRequestVerifyTokenPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify:Request-Token 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> VerifyRequestTokenAuthRequestVerifyTokenPostAsync(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            com.arpg.api.Client.ApiResponse<Object> localVarResponse = await VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfoAsync(bodyVerifyRequestTokenAuthRequestVerifyTokenPost, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify:Request-Token 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyRequestTokenAuthRequestVerifyTokenPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<com.arpg.api.Client.ApiResponse<Object>> VerifyRequestTokenAuthRequestVerifyTokenPostWithHttpInfoAsync(BodyVerifyRequestTokenAuthRequestVerifyTokenPost bodyVerifyRequestTokenAuthRequestVerifyTokenPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'bodyVerifyRequestTokenAuthRequestVerifyTokenPost' is set
            if (bodyVerifyRequestTokenAuthRequestVerifyTokenPost == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'bodyVerifyRequestTokenAuthRequestVerifyTokenPost' when calling AuthApi->VerifyRequestTokenAuthRequestVerifyTokenPost");
            }


            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bodyVerifyRequestTokenAuthRequestVerifyTokenPost;

            localVarRequestOptions.Operation = "AuthApi.VerifyRequestTokenAuthRequestVerifyTokenPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/auth/request-verify-token", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyRequestTokenAuthRequestVerifyTokenPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify:Verify 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserRead</returns>
        public UserRead VerifyVerifyAuthVerifyPost(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0)
        {
            com.arpg.api.Client.ApiResponse<UserRead> localVarResponse = VerifyVerifyAuthVerifyPostWithHttpInfo(bodyVerifyVerifyAuthVerifyPost);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify:Verify 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserRead</returns>
        public com.arpg.api.Client.ApiResponse<UserRead> VerifyVerifyAuthVerifyPostWithHttpInfo(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0)
        {
            // verify the required parameter 'bodyVerifyVerifyAuthVerifyPost' is set
            if (bodyVerifyVerifyAuthVerifyPost == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'bodyVerifyVerifyAuthVerifyPost' when calling AuthApi->VerifyVerifyAuthVerifyPost");
            }

            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bodyVerifyVerifyAuthVerifyPost;

            localVarRequestOptions.Operation = "AuthApi.VerifyVerifyAuthVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserRead>("/auth/verify", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyVerifyAuthVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify:Verify 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserRead</returns>
        public async System.Threading.Tasks.Task<UserRead> VerifyVerifyAuthVerifyPostAsync(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            com.arpg.api.Client.ApiResponse<UserRead> localVarResponse = await VerifyVerifyAuthVerifyPostWithHttpInfoAsync(bodyVerifyVerifyAuthVerifyPost, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify:Verify 
        /// </summary>
        /// <exception cref="com.arpg.api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyVerifyVerifyAuthVerifyPost"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserRead)</returns>
        public async System.Threading.Tasks.Task<com.arpg.api.Client.ApiResponse<UserRead>> VerifyVerifyAuthVerifyPostWithHttpInfoAsync(BodyVerifyVerifyAuthVerifyPost bodyVerifyVerifyAuthVerifyPost, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'bodyVerifyVerifyAuthVerifyPost' is set
            if (bodyVerifyVerifyAuthVerifyPost == null)
            {
                throw new com.arpg.api.Client.ApiException(400, "Missing required parameter 'bodyVerifyVerifyAuthVerifyPost' when calling AuthApi->VerifyVerifyAuthVerifyPost");
            }


            com.arpg.api.Client.RequestOptions localVarRequestOptions = new com.arpg.api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = com.arpg.api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = com.arpg.api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = bodyVerifyVerifyAuthVerifyPost;

            localVarRequestOptions.Operation = "AuthApi.VerifyVerifyAuthVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UserRead>("/auth/verify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyVerifyAuthVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
