/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.arpg.api.Client.OpenAPIDateConverter;

namespace com.arpg.api.Model
{
    /// <summary>
    /// BodyVerifyRequestTokenAuthRequestVerifyTokenPost
    /// </summary>
    [DataContract(Name = "Body_verify_request_token_auth_request_verify_token_post")]
    public partial class BodyVerifyRequestTokenAuthRequestVerifyTokenPost : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyVerifyRequestTokenAuthRequestVerifyTokenPost" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodyVerifyRequestTokenAuthRequestVerifyTokenPost() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyVerifyRequestTokenAuthRequestVerifyTokenPost" /> class.
        /// </summary>
        /// <param name="email">email (required).</param>
        public BodyVerifyRequestTokenAuthRequestVerifyTokenPost(string email = default(string))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for BodyVerifyRequestTokenAuthRequestVerifyTokenPost and cannot be null");
            }
            this.Email = email;
        }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BodyVerifyRequestTokenAuthRequestVerifyTokenPost {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
