name: Build and Release

on:
  push:
    branches:
      - master  # This triggers the workflow when there is a push to the master branch

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Specify your required .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Extract version from .csproj
        id: extract_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/com.arpg.api/com.arpg.api.csproj)
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release

      - name: Pack
        run: dotnet pack ./src/com.arpg.api/com.arpg.api.csproj -o ./output -c Release --no-build

      - name: List output directory
        run: ls -la ./output

      - name: Upload package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./output/*.nupkg

  release:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ./output

      - name: Read version
        run: echo "VERSION is ${{ needs.build.outputs.version }}"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ needs.build.outputs.version }}'
          release_name: 'Release v${{ needs.build.outputs.version }}'
          draft: false
          prerelease: false

      - name: Output Release URL
        run: echo "Release URL: ${{ steps.create_release.outputs.html_url }}"

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push ./output/com.arpg.api.${{ needs.build.outputs.version }}.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
